// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks_test.go -package=quote_test
//

// Package quote_test is a generated GoMock package.
package quote_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/balamuteon/plata-go-currency-quotes/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockquoteService is a mock of quoteService interface.
type MockquoteService struct {
	ctrl     *gomock.Controller
	recorder *MockquoteServiceMockRecorder
	isgomock struct{}
}

// MockquoteServiceMockRecorder is the mock recorder for MockquoteService.
type MockquoteServiceMockRecorder struct {
	mock *MockquoteService
}

// NewMockquoteService creates a new mock instance.
func NewMockquoteService(ctrl *gomock.Controller) *MockquoteService {
	mock := &MockquoteService{ctrl: ctrl}
	mock.recorder = &MockquoteServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockquoteService) EXPECT() *MockquoteServiceMockRecorder {
	return m.recorder
}

// GetLatest mocks base method.
func (m *MockquoteService) GetLatest(ctx context.Context, pair string) (domain.QuoteUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatest", ctx, pair)
	ret0, _ := ret[0].(domain.QuoteUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatest indicates an expected call of GetLatest.
func (mr *MockquoteServiceMockRecorder) GetLatest(ctx, pair any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatest", reflect.TypeOf((*MockquoteService)(nil).GetLatest), ctx, pair)
}

// GetUpdate mocks base method.
func (m *MockquoteService) GetUpdate(ctx context.Context, id string) (domain.QuoteUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdate", ctx, id)
	ret0, _ := ret[0].(domain.QuoteUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdate indicates an expected call of GetUpdate.
func (mr *MockquoteServiceMockRecorder) GetUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdate", reflect.TypeOf((*MockquoteService)(nil).GetUpdate), ctx, id)
}

// RequestUpdate mocks base method.
func (m *MockquoteService) RequestUpdate(ctx context.Context, pair, idempotencyKey string) (domain.QuoteUpdate, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestUpdate", ctx, pair, idempotencyKey)
	ret0, _ := ret[0].(domain.QuoteUpdate)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RequestUpdate indicates an expected call of RequestUpdate.
func (mr *MockquoteServiceMockRecorder) RequestUpdate(ctx, pair, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestUpdate", reflect.TypeOf((*MockquoteService)(nil).RequestUpdate), ctx, pair, idempotencyKey)
}
