// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks_test.go -package=quote_test
//

// Package quote_test is a generated GoMock package.
package quote_test

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/balamuteon/plata-go-currency-quotes/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *Mockrepository) Enqueue(ctx context.Context, id string, pair domain.CurrencyPair, idempotencyKey string) (domain.QuoteUpdate, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, id, pair, idempotencyKey)
	ret0, _ := ret[0].(domain.QuoteUpdate)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockrepositoryMockRecorder) Enqueue(ctx, id, pair, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*Mockrepository)(nil).Enqueue), ctx, id, pair, idempotencyKey)
}

// FindByID mocks base method.
func (m *Mockrepository) FindByID(ctx context.Context, id string) (domain.QuoteUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.QuoteUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockrepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*Mockrepository)(nil).FindByID), ctx, id)
}

// FindLatest mocks base method.
func (m *Mockrepository) FindLatest(ctx context.Context, pair domain.CurrencyPair) (domain.QuoteUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatest", ctx, pair)
	ret0, _ := ret[0].(domain.QuoteUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatest indicates an expected call of FindLatest.
func (mr *MockrepositoryMockRecorder) FindLatest(ctx, pair any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatest", reflect.TypeOf((*Mockrepository)(nil).FindLatest), ctx, pair)
}

// Mockqueue is a mock of queue interface.
type Mockqueue struct {
	ctrl     *gomock.Controller
	recorder *MockqueueMockRecorder
	isgomock struct{}
}

// MockqueueMockRecorder is the mock recorder for Mockqueue.
type MockqueueMockRecorder struct {
	mock *Mockqueue
}

// NewMockqueue creates a new mock instance.
func NewMockqueue(ctrl *gomock.Controller) *Mockqueue {
	mock := &Mockqueue{ctrl: ctrl}
	mock.recorder = &MockqueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockqueue) EXPECT() *MockqueueMockRecorder {
	return m.recorder
}

// Claim mocks base method.
func (m *Mockqueue) Claim(ctx context.Context, leaseDuration time.Duration) (domain.QuoteUpdate, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim", ctx, leaseDuration)
	ret0, _ := ret[0].(domain.QuoteUpdate)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Claim indicates an expected call of Claim.
func (mr *MockqueueMockRecorder) Claim(ctx, leaseDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*Mockqueue)(nil).Claim), ctx, leaseDuration)
}

// Complete mocks base method.
func (m *Mockqueue) Complete(ctx context.Context, id, leaseToken string, quote domain.Quote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, id, leaseToken, quote)
	ret0, _ := ret[0].(error)
	return ret0
}

// Complete indicates an expected call of Complete.
func (mr *MockqueueMockRecorder) Complete(ctx, id, leaseToken, quote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*Mockqueue)(nil).Complete), ctx, id, leaseToken, quote)
}

// Fail mocks base method.
func (m *Mockqueue) Fail(ctx context.Context, id, leaseToken, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fail", ctx, id, leaseToken, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fail indicates an expected call of Fail.
func (mr *MockqueueMockRecorder) Fail(ctx, id, leaseToken, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fail", reflect.TypeOf((*Mockqueue)(nil).Fail), ctx, id, leaseToken, errorMessage)
}

// Retry mocks base method.
func (m *Mockqueue) Retry(ctx context.Context, id, leaseToken string, nextAttemptAt time.Time, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retry", ctx, id, leaseToken, nextAttemptAt, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// Retry indicates an expected call of Retry.
func (mr *MockqueueMockRecorder) Retry(ctx, id, leaseToken, nextAttemptAt, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retry", reflect.TypeOf((*Mockqueue)(nil).Retry), ctx, id, leaseToken, nextAttemptAt, errorMessage)
}

// Mockprovider is a mock of provider interface.
type Mockprovider struct {
	ctrl     *gomock.Controller
	recorder *MockproviderMockRecorder
	isgomock struct{}
}

// MockproviderMockRecorder is the mock recorder for Mockprovider.
type MockproviderMockRecorder struct {
	mock *Mockprovider
}

// NewMockprovider creates a new mock instance.
func NewMockprovider(ctrl *gomock.Controller) *Mockprovider {
	mock := &Mockprovider{ctrl: ctrl}
	mock.recorder = &MockproviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockprovider) EXPECT() *MockproviderMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *Mockprovider) Fetch(ctx context.Context, pair domain.CurrencyPair) (domain.Quote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, pair)
	ret0, _ := ret[0].(domain.Quote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockproviderMockRecorder) Fetch(ctx, pair any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*Mockprovider)(nil).Fetch), ctx, pair)
}
